tabs:
  main:
    display: Main
    sections:
      -
        display: Footer
        fields:
          -
            handle: copyright
            field:
              input_type: text
              antlers: false
              type: text
              display: Copyright
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
